site_name: Single cell transcriptomics
nav:
    - Home: index.md
    - Precourse preparations: precourse.md
    - Course schedule: course_schedule.md
    - Day 1:
      - Setup: day1/setup.md
      - Introduction & cellranger: day1/introduction_cellranger.md
      - Analysis tools and QC: day1/analysis_tools_qc.md
      - Normalization and scaling: day1/normalization_scaling.md
    - Day 2:
      - Dimensionality reduction: day2/dimensionality_reduction.md
      - Integration: day2/integration.md
      - Clustering: day2/clustering.md
      - Cell annotation: day2/cell_annotation.md
    - Day 3:
      - Differential gene expression: day3/differential_gene_expression.md
      - Enrichment analysis: day3/enrichment_analysis.md
      - Advanced analyses: day3/advanced_analyses.md
      - Trajectory analysis (extra): day3/trajectory_analysis.md

theme:
  name: material
  custom_dir: overrides
  logo: assets/images/SIB_logo.svg
  favicon: assets/images/SIB_logo.svg
  features:
    - announce.dismiss

# Repository
repo_name: sib-swiss/single-cell-training-archived
repo_url: https://github.com/sib-swiss/single-cell-training-archived

markdown_extensions:
  - abbr
  - def_list
  - footnotes
  - tables
  - admonition
  - codehilite:
      guess_lang: false
  - sane_lists
  - smarty
  - toc
  - pymdownx.superfences
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons


extra_css:
  - stylesheets/extra.css

extra:
  version:
    provider: mike
  analytics:
    provider: google
    property: G-1H5B39PY7V
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

copyright: >
  Copyright &copy; 2021 - 2022 SIB Swiss Institute of Bioinformatics –
  <a href="#__consent">Change cookie settings</a>
